service: karsrail

custom:
  bucket: karsrail

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  memorySize: 256
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  cron:
    handler: handler.run
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - schedule: rate(3 minutes)
